title: Department of Statistics
author:
  name: Mrinal
  email: mrinalvbu@gmail.com
  github: mrinalcs
email: na
description: >- 
  Department of Statistics Visva-Bharati.
baseurl: "" 
url: "https://vbstat.github.io" 
github_username:  vbstat

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title

collections:
  pages:
    output: true

exclude:
  - data.json
  - README.md
